FROM python:3.11

# Set a directory for the app
#C:\Users\Omers\Desktop
WORKDIR /usr/src/hello-world 

# Copy all the files to the container
COPY . .

# Run the command
CMD ["python", "hello.py"]